apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-xcnksss
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-xcnksss
    app.kubernetes.io/part-of: jeff-test
  name: devfile-sample-go-basic-xcnksss
  namespace: jephilli-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-xcnksss
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-xcnksss
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:be5fa8cf204d43269d8000b1e74e8cb716669da1c69a99c2323743c57ef0bbae
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
