apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jeff-go-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jeff-go-basic
    app.kubernetes.io/part-of: jeff-test
  name: jeff-go-basic
  namespace: jephilli-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: jeff-go-basic
status:
  loadBalancer: {}
